---
port: 5000
host: 'localhost'
googleOauth:
  clientId: '238455601010-q1upaaa17s4q3ku3sikr253d4q6pquen.apps.googleusercontent.com'
  clientSecret: 'Tp0i4lI-DfdIA9Gs3OzJEGKl'
supabase:
  url: "https://vqqjrxggizczqfdfthzl.supabase.co"
  publicKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyMDA1MTM2MCwiZXhwIjoxOTM1NjI3MzYwfQ.HdsMVmnUd2fmsUccGCxEEIcC57GqGnBXVLvJXBpSA-k"
  serviceKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjIwMDUxMzYwLCJleHAiOjE5MzU2MjczNjB9.qWQY2E5ZHZsypQ-mMpiTHa0dYmTVcsn0D2_ptZ8wbYc"